### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by donalm** [Ahuge/NukeParser#2]
Hey Alex - any chance you could slap a (liberal) license on this repo? It looks really useful, but I'm unable to use it.

Thanks

DJM

**Comment by Ahuge** [comment]
I 100% can.

I will have to mark it as pretty unmaintained, I can't remember where we ended with it.

**Comment by Ahuge** [comment]
Boom, done

**Comment by Ahuge** [comment]
You may also be interested in a more recent attempt called [stunning barnacle](https://github.com/Ahuge/stunning-barnacle).

It is equally unmaintained but might be useful

**Comment by donalm** [comment]
Brilliant - MIT is perfect. Thanks so much Alex!
I'll check out the other repo too.
